# Generated by Django 4.2 on 2026-05-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QGenieAIapp', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_questions', to='QGenieAIapp.uploadedfile')),
            ],
        ),
    ]
