# Generated by Django 4.2 on 2026-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QGenieAIapp', '0003_normalquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='include_answers',
            field=models.BooleanField(default=True),
        ),
    ]
