# Generated by Django 4.2 on 2026-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QGenieAIapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('night', 'Night Mode')], default='dark', max_length=20),
        ),
    ]
